 -- liquibase formatted sql

 -- changeset tav:ads_1
 CREATE TABLE ads(
 id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 user_id INT NOT NULL,
 image_url VARCHAR(255),
 price INT NOT NULL,
 title VARCHAR(32) NOT NULL,
 description VARCHAR(64) NOT NULL,
 CONSTRAINT "PK_ads_id" PRIMARY KEY (id),
 CONSTRAINT "FK_ads_users" FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT "ads_title_length_min" CHECK (char_length(title) > 3),
 CONSTRAINT "ads_description_length_min" CHECK (char_length(description) > 7),
 CONSTRAINT "ads_price_min-max" CHECK (price > 0 AND price < 10000001)
 );