 -- liquibase formatted sql

 -- changeset tav:comments_1
 CREATE TABLE comments(
 id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 user_id INT NOT NULL,
 ad_id INT NOT NULL,
 created_at BIGINT NOT NULL,
 "text" VARCHAR(64) NOT NULL,
 CONSTRAINT "PK_comments_id" PRIMARY KEY (id),
 CONSTRAINT "FK_comments_users" FOREIGN KEY (user_id) REFERENCES users(id),
 CONSTRAINT "FK_comments_ads" FOREIGN KEY (ad_id) REFERENCES ads(id),
 CONSTRAINT "comments_text_min-max" CHECK (char_length("text") > 7)
 );